<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(ResolverTargetFramework);net472</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DisableRuntimeMarshalling Condition="'$(TargetFramework)' == '$(ResolverTargetFramework)'">true</DisableRuntimeMarshalling>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Deployment.DotNet.Releases" />
  </ItemGroup>

</Project>
